name: ci
on:
  push:
    branches: ['main']
jobs:
  build_14:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push 14
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: papodaca/postgres:14,papodaca/postgres:latest
  build_13:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push 13
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: PG_VERSION=13
          push: true
          tags: papodaca/postgres:13
  build_12:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push 14
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: papodaca/postgres:14,papodaca/postgres:latest
      - name: Build and push 12
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: PG_VERSION=12
          push: true
          tags: papodaca/postgres:12
